name: micro_app_login
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0-428.0.dev <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  micro_core:
    git:
      url: https://github.com/Morpa/micro-core.git
      ref: v1.0.0

  micro_commons_design_system:
    git:
      url: https://github.com/Morpa/micro-commons-design-system.git
      ref: v1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
